/** GEA sales-plan read-only page mounted through dsh Web slots. */
import React, { useEffect, useRef, useState } from 'react';

export const inject = ['slots', 'layout', 'locale', 'connection', 'sessions', 'uiWorkspace'];
const zh = {
  title: 'GEA 销售计划', tag: '独立只读插件', intro: '查询销售计划、查看版本与 SKU，并将明确选择的数据交给 dsh 会话。', login: '飞书扫码登录', refresh: '查询销售计划', fixture: '载入演示数据', send: '发送选中记录到会话', signedOut: '尚未登录 GEA', signedIn: '已登录', environment: 'GEA 环境', qr: '请使用飞书扫描二维码', pending: '等待扫码确认', expired: '二维码已过期，请重新登录', live: '真实 GEA 数据 · 只读', demo: '演示数据 · 非真实业务', none: '还没有查询结果', empty: '本次查询没有记录', period: '销售周期', allPeriods: '全部周期', planType: '计划类型', statusFilter: '状态码', allStatuses: '全部状态', page: '页码', apply: '查询', details: '查看详情', versions: '查看版本', skus: '查看 SKU', close: '关闭', selected: '选择记录', dealer: '经销商', type: '计划类型', status: '状态码', qty: '当前数量', target: '目标数量', unknown: '未提供', time: '查询时间', total: '查询总数', coverage: '当前页数据；会话只接收明确选中的记录及已查看的附加信息。', receipt: '分析配置由 dsh profile 决定；演示回执不是真实 AI 分析。', failure: '操作未完成', busy: '处理中…', help: '登录仅保留在本次服务进程中，重启后需重新登录。', noPeriods: '暂无可用销售周期', allTypes: '全部类型', range: '数据范围',
};
const en = { ...zh, title: 'GEA sales plans', tag: 'Independent read-only plugin', intro: 'Query plans, inspect versions and SKUs, and send an explicit selection to a dsh session.', login: 'Sign in with Lark QR', refresh: 'Query sales plans', fixture: 'Load demo data', send: 'Send selected record to session', signedOut: 'Not signed in to GEA', signedIn: 'Signed in', environment: 'GEA environment', qr: 'Scan with Lark', pending: 'Waiting for confirmation', expired: 'QR expired. Sign in again.', live: 'Live GEA data · read only', demo: 'Demo data · not real business', none: 'No query yet', empty: 'No records returned', period: 'Period', allPeriods: 'All periods', planType: 'Plan type', statusFilter: 'Status code', allStatuses: 'All statuses', page: 'Page', apply: 'Query', details: 'View details', versions: 'View versions', skus: 'View SKUs', close: 'Close', selected: 'Select record', dealer: 'Dealer', type: 'Plan type', status: 'Status code', qty: 'Current quantity', target: 'Target quantity', unknown: 'Not provided', time: 'Fetched at', total: 'Total', coverage: 'Current page; the session receives the explicit selection and inspected details.', receipt: 'Analysis is selected by the dsh profile; the demo receipt is not real AI analysis.', failure: 'Operation failed', busy: 'Working…', help: 'Login remains in this server process only. Restart requires signing in again.', noPeriods: 'No periods available', allTypes: 'All types', range: 'Data range' };

export function apply(ctx) {
  ctx.effect(() => ctx.locale.register('geaProof', { zh, en }));
  const t = ctx.locale.bind('geaProof');
  async function rpc(endpoint, payload = {}) { const response = await fetch('/api/gea-proof/' + endpoint, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error('HOST_HTTP_' + response.status); const result = await response.json(); if (!result.ok) { const error = new Error(result.error.message); error.code = result.error.code; throw error; } return result.value; }
  function Page() {
    const [status, setStatus] = useState(null); const [qr, setQr] = useState(null); const [qrState, setQrState] = useState('pending'); const [periods, setPeriods] = useState([]); const [data, setData] = useState(null); const [selected, setSelected] = useState(0); const [detail, setDetail] = useState(null); const [version, setVersion] = useState(null); const [skus, setSkus] = useState(null); const [filters, setFilters] = useState({ periodId: '', planTypeCode: '', status: '', pageNo: 1 }); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const loginGeneration = useRef(0); const sendGeneration = useRef(false);
    useEffect(() => { rpc('status').then(setStatus).catch(e => setError(e.message)); }, []);
    useEffect(() => { if (!qr || qrState !== 'pending') return undefined; const generation = loginGeneration.current; let disposed = false; let timer; const poll = async () => { try { const result = await rpc('login/poll'); if (disposed || generation !== loginGeneration.current) return; setQrState(result.status); if (result.status === 'authenticated') { setStatus(result); setQr(null); } else if (result.status === 'pending') timer = setTimeout(poll, 2500); } catch (e) { if (!disposed) { setError(e.message); setQrState('failed'); } } }; timer = setTimeout(poll, 2500); return () => { disposed = true; clearTimeout(timer); }; }, [qr, qrState]);
    const act = fn => async () => { setBusy(true); setError(''); try { await fn(); } catch (e) { setError(e.code || e.message); } finally { setBusy(false); } };
    const query = act(async () => { const [nextPeriods, nextData] = await Promise.all([periods.length ? Promise.resolve(periods) : rpc('periods'), rpc('plans', filters)]); setPeriods(nextPeriods); setData(nextData); setSelected(0); setDetail(null); setVersion(null); setSkus(null); });
    const inspect = (endpoint, payload, setter) => act(async () => setter(await rpc(endpoint, payload)));
    const send = act(async () => { if (sendGeneration.current) throw new Error('ANALYSIS_ALREADY_RUNNING'); sendGeneration.current = true; try { const prepared = await rpc('prepare', { index: selected, detail: detail?.data, version: version?.record, skus: skus?.records ?? skus }); const current = await rpc('status'); const sessionId = await ctx.sessions.create({ cwd: current.workspace }); const result = await ctx.sessions.binding(sessionId).session.prompt([{ type: 'text', text: prepared.prompt }], 'queue'); if (!result.ok) throw new Error(result.error.message); ctx.uiWorkspace.openSession(sessionId); ctx.layout.selectPanel(null); } finally { sendGeneration.current = false; } });
    const buttonStyle = { border: '1px solid #a5b4c9', borderRadius: 7, padding: '8px 12px', cursor: 'pointer', fontSize: 14, background: '#fff', color: '#172b43' }, inputStyle = { ...buttonStyle, cursor: 'default', padding: '8px' }; const records = data?.records ?? [];
    return <div style={{ overflow: 'auto', height: '100%', padding: '32px 38px', color: '#172b43', background: '#f4f7fb', fontFamily: 'system-ui' }}><div style={{ maxWidth: 1100, margin: '0 auto' }}><div style={{ color: '#436594', fontSize: 12, marginBottom: 9 }}>{t('tag')}</div><h1 style={{ fontSize: 28, fontWeight: 650, margin: '0 0 12px' }}>{t('title')}</h1><p style={{ color: '#536377' }}>{t('intro')}</p>
      <section style={{ padding: 20, margin: '24px 0', background: '#fff', border: '1px solid #d8e1ee', borderRadius: 10 }}><p>{status?.authenticated ? `${t('signedIn')}：${status.user.name}` : t('signedOut')}</p>{status?.source && <p style={{ fontSize: 13, color: '#65758a', overflowWrap: 'anywhere' }}>{t('environment')}：{status.source}</p>}<div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', margin: '14px 0' }}><button style={buttonStyle} disabled={busy} onClick={act(async () => { loginGeneration.current += 1; setData(null); setStatus({ authenticated: false, source: status?.source }); setQr(await rpc('login/start')); setQrState('pending'); })}>{t('login')}</button><button style={{ ...buttonStyle, background: '#1b4f8c', color: '#fff' }} disabled={busy || !status?.authenticated} onClick={query}>{t('refresh')}</button><button style={buttonStyle} disabled={busy} onClick={act(async () => { setData(await rpc('fixture')); setSelected(0); })}>{t('fixture')}</button></div><small style={{ color: '#65758a' }}>{t('help')}</small>{qr && <div style={{ marginTop: 18 }}><p>{t('qr')}</p><img width="256" height="256" src={qr.image} alt={t('qr')} /><p>{t(qrState === 'expired' ? 'expired' : 'pending')}</p></div>}</section>
      {status?.authenticated && <section style={{ padding: 16, margin: '16px 0', background: '#fff', border: '1px solid #d8e1ee', borderRadius: 10, display: 'flex', gap: 10, flexWrap: 'wrap', alignItems: 'center' }}><label>{t('period')} <select style={inputStyle} value={filters.periodId} onChange={e => setFilters({ ...filters, periodId: e.target.value, pageNo: 1 })}><option value="">{t('allPeriods')}</option>{periods.map(p => <option key={p.periodId} value={p.periodId}>{p.periodName || p.periodCode || p.periodId}</option>)}</select></label><label>{t('planType')} <input style={inputStyle} value={filters.planTypeCode} onChange={e => setFilters({ ...filters, planTypeCode: e.target.value, pageNo: 1 })} placeholder={t('allTypes')} /></label><label>{t('statusFilter')} <input style={{ ...inputStyle, width: 70 }} value={filters.status} onChange={e => setFilters({ ...filters, status: e.target.value, pageNo: 1 })} placeholder={t('allStatuses')} /></label><label>{t('page')} <input style={{ ...inputStyle, width: 55 }} type="number" min="1" value={filters.pageNo} onChange={e => setFilters({ ...filters, pageNo: Math.max(1, Number(e.target.value) || 1) })} /></label><button style={{ ...buttonStyle, background: '#1b4f8c', color: '#fff' }} disabled={busy} onClick={query}>{t('apply')}</button></section>}
      {busy && <p role="status">{t('busy')}</p>}{error && <p role="alert" style={{ color: '#a12727' }}>{t('failure')}：{error}</p>}{data && <section style={{ padding: 20, background: '#fff', border: '1px solid #d8e1ee', borderRadius: 10 }}><strong style={{ color: data.source === 'GEA_LIVE_READONLY' ? '#157451' : '#9b6200' }}>{t(data.source === 'GEA_LIVE_READONLY' ? 'live' : 'demo')}</strong><p style={{ fontSize: 13, color: '#65758a' }}>{t('time')}：{data.fetchedAt} · {t('total')}：{data.total} · {t('range')}：{data.current}/{data.size}</p><div style={{ overflowX: 'auto' }}><table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}><thead><tr>{['selected', 'dealer', 'type', 'status', 'qty', 'target'].map(key => <th key={key} style={{ textAlign: 'left', padding: 10, borderBottom: '1px solid #d8e1ee' }}>{t(key)}</th>)}</tr></thead><tbody>{records.map((row, index) => <tr key={row.planId || index} style={{ background: selected === index ? '#edf4ff' : undefined }}><td style={{ padding: 12 }}><input type="radio" name="plan" aria-label={`${t('selected')} ${index + 1}`} checked={selected === index} onChange={() => { setSelected(index); setDetail(null); setVersion(null); setSkus(null); }} /></td>{[row.dealerName, row.planTypeCode, row.status, row.currentQty, row.targetQty].map((value, cell) => <td key={cell} style={{ padding: 10 }}>{value ?? t('unknown')}</td>)}</tr>)}</tbody></table></div>{!records.length && <p>{t('empty')}</p>}<p style={{ color: '#65758a', fontSize: 13 }}>{t('coverage')}</p>{records.length > 0 && <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}><button style={buttonStyle} disabled={busy} onClick={inspect('detail', { planId: records[selected].planId }, setDetail)}>{t('details')}</button><button style={buttonStyle} disabled={busy} onClick={inspect('versions', { planId: records[selected].planId }, setVersion)}>{t('versions')}</button><button style={buttonStyle} disabled={busy || !version} onClick={inspect('skus', { versionId: version?.record?.versionId || version?.versionId }, setSkus)}>{t('skus')}</button><button style={{ ...buttonStyle, background: '#1b4f8c', color: '#fff' }} disabled={busy} onClick={send}>{t('send')}</button></div>}</section>}
      {detail && <Info title={t('details')} value={detail.data} close={() => setDetail(null)} t={t} />}{version && <Info title={t('versions')} value={version.records ?? version} close={() => setVersion(null)} t={t} select={record => setVersion({ ...version, record })} />}{skus && <Info title={t('skus')} value={skus.records ?? skus} close={() => setSkus(null)} t={t} />}<p style={{ color: '#65758a', fontSize: 13, marginTop: 22 }}>{t('receipt')}</p></div></div>;
  }
  function Info({ title, value, close, t, select }) { const list = Array.isArray(value) ? value : []; return <section style={{ padding: 16, margin: '16px 0', background: '#fff', border: '1px solid #d8e1ee', borderRadius: 10 }}><strong>{title}</strong><button style={{ float: 'right', border: 0, background: 'transparent', cursor: 'pointer' }} onClick={close}>{t('close')}</button>{select && list.length > 0 && <div style={{ margin: '12px 0', display: 'flex', gap: 8, flexWrap: 'wrap' }}>{list.map((record, index) => <button key={record.versionId || record.id || index} style={{ border: '1px solid #a5b4c9', borderRadius: 6, padding: '6px 9px', background: '#fff' }} onClick={() => select(record)}>#{index + 1} {record.versionId || record.id || ''}</button>)}</div>}<pre style={{ whiteSpace: 'pre-wrap', overflow: 'auto', maxHeight: 360, fontSize: 12 }}>{JSON.stringify(value, null, 2)}</pre></section>; }
  function Icon({ size = 18 }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 8h8M8 12h8M8 16h4" /></svg>; }
  ctx.slots.inject('main', () => ctx.slots.register({ name: 'main', key: 'gea-proof', locale: 'geaProof' }, Page)); ctx.slots.inject('sidebar.panellist', () => ctx.slots.register({ name: 'sidebar.panellist', id: 'gea-proof', label: () => t('title'), order: 5, locale: 'geaProof' }, Icon));
}
